
name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [primary, dr]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region == 'primary' && 'us-east-1' || 'us-east-2' }}

      - name: Choose the region
        run: |
          cd terraform/${{ matrix.region }}
      
      - name: Choose the region
        run: |    
          terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
